---
title: "mn_elections_playground"
author: "Luke Kolar"
date: "10/3/2020"
output: html_document
---

```{r, message = F}

## Loading necessary packages...

library(geojsonio)
library(rgdal)
library(raster)
library(rgeos)
library(cowplot)
library(gridExtra)
library(ggthemes)
library(rcartocolor)
library(zipcodeR)
library(smoothr)
library(broom)
library(sf)
library(lwgeom)
library(janitor)
library(readxl)

# `tidyverse` last...

library(tidyverse)

```

```{r}

## Important recycled objects:

elec.col.names <- c("state", "county_id", "precinct_name",
                    "office_id", "office_name", "district", 
                    "candidate_order_code", "candidate_name",
                    "suffix", "incumbent_code", "party_affiliation",
                    "num_precincts_reporting", "total_num_precincts_voting",
                    "candidate_votes", "candidate_percent_vote", "total_race_votes")

prec.col.names <- c("county_id", "precinct_id", "precinct_name", "cong_dist",
                    "leg_dist", "ctycomdist", "jud_dist", "sw_dist", "mcd_code", "sd_num")

county_ids <- read.delim("relevant_county_data/county_ids.txt", 
  sep = ";", header = FALSE, col.names = c("county_id", "county_name", 
                                           "county_num_precincts")) %>% 
  mutate(county_name = str_to_title(county_name)) %>% 
  mutate(county_name = str_replace(county_name, " Of The ", " of the ")) %>% 
  mutate(county_name = str_replace(county_name, " Qui ", " qui ")) %>% 
  mutate(county_name = trimws(county_name, which = c("right"))) %>% 
  mutate(county_name = str_replace(county_name, "Saint Louis", "St. Louis")) %>% 
  mutate(county_name = str_replace(county_name, "Mcleod", "McLeod"))

county_positions <- tibble(title = c("Commissioner", "Auditor", "Treasurer", 
                                     "Auditor/Treasurer", "Recorder", "Sheriff", "Attorney", 
                                     "Soil and Water Supervisor", "Surveyor", 
                                     "Park Commissioner", "Coroner"),
                           code = c("COM", "AUD", "TRS", "A&T", "REC", "SHF", "ATR",
                                    "S&W", "SRV", "PCM", "COR"))

```


```{r}

## Practicing with the 2018 dataset

sb_2018 <- read.delim("relevant_schooldist_data/schooldist_races_datasets/2018_schoolboard.txt", 
  sep = ";", header = FALSE, col.names = elec.col.names) %>% 
  select(office_name, candidate_name, total_num_precincts_voting, candidate_votes, 
         candidate_percent_vote, total_race_votes) %>% 
  mutate(special = ifelse(grepl("Special", office_name), TRUE, FALSE)) %>% 
  mutate(position = ifelse(grepl("Position", office_name), 
                           str_match(office_name, "(?<=Position )[:digit:]*"), 
                           "at-large")) %>% 
  mutate(district = ifelse(grepl("District [[:digit:]]", office_name), 
                           str_match(office_name, "(?<=District )[:digit:]*"), 
                           ifelse(grepl("District", office_name), 
                                  str_match(office_name, 
                                            "(?<=Member ).*(?= District)"), NA))) %>% 
  mutate(elect = ifelse(grepl("Elect [[:digit:]]", office_name), 
                        str_match(office_name, "(?<=Elect )[:digit:]*"),
                        1)) %>% 
  mutate(sd_type = ifelse(grepl("ISD", office_name), "ISD",
                          ifelse(grepl("SDD", office_name), "SSD", "CSD"))) %>% 
  mutate(sd_code = ifelse(sd_type == "ISD", 1,
                          ifelse(sd_type == "SSD", 3, 2))) %>% 
  mutate(sd_code = sprintf("%02d", sd_code)) %>% 
  mutate(sd_num = ifelse(grepl("ISD", office_name), 
                     str_extract(office_name, "(?<=ISD #)[:digit:]*"),
                     ifelse(grepl("SSD", office_name), 
                            str_extract(office_name, "(?<=SSD #)[:digit:]*"),
                            "none"))) %>% 
  mutate(sd_num = as.numeric(sd_num)) %>% 
  mutate(sd_num = sprintf("%04d", sd_num)) %>% 
  mutate(elect = as.numeric(elect)) %>% 
  select(candidate_name, sd_num, sd_code, sd_type,
         total_num_precincts_voting, elect, 
         position, district, special, office_name)
  
sb_2018_grouped <- sb_2018 %>% 
  group_by(sd_num, sd_code, total_num_precincts_voting) %>% 
  summarise(num_candidates = n()) %>% 
  ungroup()

```

```{r, eval = F}

## Potentially important tests for school board data:

test_year <- 2018
sb_tests <- read.delim(paste0("relevant_schooldist_data/schooldist_races_datasets/",
                              test_year, "_schoolboard.txt"), 
                       sep = ";", header = FALSE, col.names = elec.col.names)

# all precincts reporting?

sb_tests %>% 
  mutate(test = num_precincts_reporting - total_num_precincts_voting) %>% 
  group_by(test) %>% 
  summarize(n = n())

# all non-partisan?

sb_tests %>% 
  group_by(party_affiliation) %>% 
  summarize(n = n())

# no suffixes?

sb_tests %>% 
  group_by(suffix) %>% 
  summarize(n = n())

# incumbent codes?

sb_tests %>% 
  group_by(incumbent_code) %>% 
  summarize(n = n())

```

```{r}

## Practice map with oversimplified variable

schooldist_map_18_19_raw <- readOGR( 
  dsn = paste0(getwd(),"/relevant_schooldist_data/shp_bdry_school_district_2010s/"), 
  layer = "school_district_boundaries_2018_19",
  verbose = FALSE) 

schooldist_map_18_19_messy <- spTransform(schooldist_map_18_19_raw, 
            CRS("+proj=longlat +datum=WGS84 +no_defs +ellps=WGS84 +towgs84=0,0,0"))

schooldist_map_18_19 <- st_as_sf(schooldist_map_18_19_messy) %>% 
  rename(sd_code = UNI_TYP,
         sd_num = UNI_MAJ,
         dist_name = UNI_NAM) %>% clean_names() %>%
  mutate(sd_num = sprintf("%04d", sd_num),
         sd_code = sprintf("%02d", sd_code)) %>% 
  select(sd_code, sd_num, dist_name, sqmiles, acres, geometry) 
  
school_dist_elections_18 <- schooldist_map_18_19 %>% 
  full_join(sb_2018_grouped, by = c("sd_code", "sd_num"))

ggplot(school_dist_elections_18, aes(fill = num_candidates)) + 
  geom_sf(color = "grey30", lwd = 0.25) + 
  theme_void() + scale_fill_gradient(low = "white", high = "red")

```

```{r}

## Inspecting and cleaning county races

clean_county <- function(year = c(2000:2020), type = c("general", "primary")){
  
  election <- if(type == "general"){"gen"}else{if(type == "primary"){"primary"}else{
    stop("Variable \`type\` must be \"general\" or \"primary\" (note quotations)")}}
  
  read.delim(paste0("relevant_county_data/county_races_datasets/", 
                    year, "_county_", election, ".txt"), 
  sep = ";", header = FALSE, col.names = elec.col.names) %>% clean_names() %>% 
  select(county_id, office_id:candidate_name,
         total_num_precincts_voting:total_race_votes) %>% 
  mutate(office_name = str_to_title(office_name)) %>%
  filter(!grepl(c("Question"), office_name)) %>% 
  filter(grepl(c("Soil|County"), office_name)) %>% 
  mutate(special = ifelse(grepl("Special", office_name), TRUE, FALSE)) %>% 
  mutate(office_name = str_remove(office_name, "Special Election For ")) %>% 
  mutate(district = as.numeric(ifelse(grepl("District [[:digit:]]", office_name), 
                           str_match(office_name, "(?<=District )[:digit:]*"), 
                           ifelse(grepl("District", office_name), 
                                  str_match(office_name, 
                                            "(?<=Member ).*(?= District)"), NA)))) %>% 
  mutate(office_name = str_remove(office_name, "County ")) %>% 
  mutate(office_name = str_remove(office_name, " District.*$")) %>% 
  mutate(office_name = str_replace(office_name, " And ", " and ")) %>% 
  mutate(office_name = str_replace(office_name, "Auditor - Treasurer",
                                   "Auditor/Treasurer")) %>% 
  mutate(other_county_id = ifelse(grepl("Marshall-Beltrami", office_name),
                               ifelse(county_id == 4, 45, 4), NA)) %>% 
  mutate(office_name = str_remove(office_name, "Marshall-Beltrami ")) %>% 
  mutate(candidate_name = str_to_title(candidate_name))
  
}

```

```{r}

## Using simple metrics to explore County Commissioner election data

# function for pulling basic commissioner numbers 

comm.elections.info <- function(year, type, pull){
  summary_df <- clean_county(year, type) %>% 
    select(county_id, office_name, district, candidate_name, candidate_votes, 
           candidate_percent_vote, special) %>% 
    filter(office_name == "Commissioner") %>% 
    rename(ctycomdist = district) %>% 
    group_by(county_id, office_name, ctycomdist) %>% 
    summarize(num_candidates = n() - ifelse(type == "general", 1, 0)) %>% 
    ungroup() %>% 
    summarize(avg = mean(num_candidates),
              num = n())
  
  elections <- summary_df$num[[1]]
  avg.cand <- summary_df$avg[[1]]
  
  ifelse(pull == "elections", elections, avg.cand)
  }

# creating a table to explore change over time

comm_e <- tibble(
  year = c(2004, 2006, 2008, 2010, 2012, 2014, 2016, 2018),
  prim.elections = c(rep(NA, 8)),
  prim.avg.cand = c(rep(NA, 8)),
  gen.elections = c(rep(NA, 8)),
  gen.avg.cand = c(rep(NA, 8))
  ) %>% 
  mutate(prim.elections = as.numeric(prim.elections),
         prim.avg.cand = as.numeric(prim.avg.cand),
         gen.elections = as.numeric(gen.elections),
         gen.avg.cand = as.numeric(gen.avg.cand))

for(i in 1:nrow(comm_e)){
  comm_e$prim.elections[[i]] <- comm.elections.info(comm_e$year[[i]], "primary", "elections")
  comm_e$prim.avg.cand[[i]] <- comm.elections.info(comm_e$year[[i]], "primary", "avg.cand")
  comm_e$gen.elections[[i]] <- comm.elections.info(comm_e$year[[i]], "general", "elections")
  comm_e$gen.avg.cand[[i]] <- comm.elections.info(comm_e$year[[i]], "general", "avg.cand")
}

# creating line plots to visualize

ggplot(comm_e, aes(x = year)) + 
  geom_line(aes(y = prim.avg.cand, color = "Primary"), size = 0.8, linetype = 1) + 
  geom_line(aes(y = gen.avg.cand, color = "General"), size = 0.8, linetype = 1) + 
  scale_x_continuous(breaks = c(2004, 2006, 2008, 2010, 2012, 2014, 2016, 2018),
                     labels = c(2004, 2006, 2008, 2010, 2012, 2014, 2016, 2018)) + 
  scale_y_continuous(breaks = c(1.5, 2, 2.5, 3, 3.5, 4),
                     labels = c(1.5, 2, 2.5, 3, 3.5, 4), limits = c(1.25, 4.25)) + 
  scale_colour_manual("", breaks = c("Primary", "General"),
                        labels = c("Primary", "General"), values = c("blue", "red")) + 
  labs(x = NULL, y = "average candidates in each election, excluding write-ins",
       title = "Average MN County Commissioner Candidates in\nPrimary and General Elections",
       caption = "note: county commissioner elections occur biennally;\ncounty redistricting is effective in years ending in \"2\"") +
  theme_few() + theme(panel.grid.major = element_line(color = "grey"),
                      panel.grid.minor = element_line(color = "lightgrey"),
                      plot.title = element_text(face = "bold", size = 14, hjust = 0.5),
                      plot.caption = element_text(face = "italic", size = 7),
                      axis.title.y = element_text(size = 8),
                      axis.text = element_text(face = "bold", color = "black"),
                      legend.text = element_text(face = "italic", color = "black"),
                      panel.background = element_rect(fill = "azure"))

ggplot(comm_e, aes(x = year)) + 
  geom_line(aes(y = gen.elections, color = "General"), size = 0.7, linetype = 1) +
  geom_line(aes(y = prim.elections, color = "Primary"), size = 0.7, linetype = 1) + 
  scale_x_continuous(breaks = c(2004, 2006, 2008, 2010, 2012, 2014, 2016, 2018),
                     labels = c(2004, 2006, 2008, 2010, 2012, 2014, 2016, 2018)) + 
  scale_colour_manual("", breaks = c("Primary", "General"),
                        labels = c("Primary", "General"), values = c("blue", "red")) + 
  labs(x = NULL, y = "total number of county commissioner elections",
       title = "Total MN County Commissioner Elections, by Type",
       caption = "note: county commissioner elections occur biennally;\ncounty redistricting is effective in years ending in \"2\"") +
  theme_few() + theme(panel.grid.major = element_line(color = "grey"),
                      panel.grid.minor = element_line(color = "lightgrey"),
                      plot.title = element_text(face = "bold", size = 14, hjust = 0.5),
                      plot.caption = element_text(face = "italic", size = 7),
                      axis.title.y = element_text(size = 8),
                      axis.text = element_text(face = "bold", color = "black"),
                      legend.text = element_text(face = "italic", color = "black"),
                      panel.background = element_rect(fill = "azure"))

ggplot(comm_e, aes(x = year)) + 
  geom_line(aes(y = 100*(prim.elections/gen.elections)), size = 0.7, linetype = 1) + 
  scale_x_continuous(breaks = c(2004, 2006, 2008, 2010, 2012, 2014, 2016, 2018),
                     labels = c(2004, 2006, 2008, 2010, 2012, 2014, 2016, 2018)) + 
  scale_y_continuous(limits = c(10, 40), breaks = c(10, 15, 20, 25, 30, 35, 40),
                     labels = c("10%", "15%", "20%", "25%", "30%", "35%", "40%")) + 
  labs(x = NULL, y = "% of elections beginning with primary contest",
       title = "Percent of MN County Commissioner Elections Beginning with Primary Contest",
       subtitle = "May indicate competitiveness of county-level elections",
       caption = "note: county commissioner elections occur biennally;\ncounty redistricting is effective in years ending in \"2\"") +
  theme_few() + theme(panel.grid.major = element_line(color = "grey"),
                      panel.grid.minor = element_line(color = "lightgrey"),
                      plot.title = element_text(face = "bold", size = 12, hjust = 0.5),
                      plot.subtitle = element_text(face = "italic", hjust = 0.5, size = 11),
                      plot.caption = element_text(face = "italic", size = 7),
                      axis.title.y = element_text(size = 8),
                      axis.text = element_text(face = "bold", color = "black"),
                      legend.text = element_text(face = "italic", color = "black"),
                      panel.background = element_rect(fill = "azure"))

```

```{r}

## Practicing with county maps

counties_map_raw <- readOGR( 
  dsn = paste0(getwd(),"/relevant_county_data/shp_bdry_counties/"), 
  layer = "mn_county_boundaries",
  verbose = FALSE) 

counties_map_messy <- spTransform(counties_map_raw, 
            CRS("+proj=longlat +datum=WGS84 +no_defs +ellps=WGS84 +towgs84=0,0,0"))

counties_map <- st_as_sf(counties_map_messy) %>% 
  rename(county_id = COUN,
         county_name = CTY_NAME) %>% clean_names() %>%
  select(county_id, county_name, cty_abbr, geometry) %>% 
  mutate(county_name = as.character(county_name),
         county_id = as.integer(county_id)) %>% 
  group_by(county_name) %>% 
  summarize(geometry = st_union(geometry))

county_pop_2019 <- read_xlsx("relevant_county_data/county_pop_estimates_2019.xlsx",
                             skip = 1,
                             col_names = c("county_id", "county_name", "total_pop",
                                           "pop_in_households", "pop_in_group_quarters",
                                           "num_households", "persons_per_household")) %>% 
                   mutate(county_id = as.numeric(str_remove(county_id, "^0+"))) %>% 
                   filter(!is.na(county_id)) %>% 
                   mutate(county_id = as.integer(county_id)) %>% 
                   mutate(county_id = (county_id + 1)/2)

county_demo_2010 <- read_xlsx("general_data/2010_census_demographics.xlsx", sheet = "Counties",
                              skip = 3, col_names = c("county_name", "total_pop",
                                                      "num_0.17", "perc_0.17", "perc_fem_0.17",
                                                      "num_18.24", "perc_18.24", "perc_fem_18.24",
                                                      "num_25.44", "perc_25.44", "perc_fem_25.44",
                                                      "num_45.64", "perc_45.64", "perc_fem_45.64",
                                                      "num_65p", "perc_65p", "perc_fem_65p")) %>% 
                    mutate(county_name = str_remove(county_name, " County"))

counties_pop_map_2019 <- counties_map %>% 
  full_join(county_pop_2019, by = c("county_name"))
  
counties_demo_map_2010 <- counties_map %>% 
  full_join(county_demo_2010, by = c("county_name"))

p1 <- ggplot(counties_demo_map_2010, aes(fill = (perc_25.44 + perc_45.64) / 
                                                   (perc_0.17 + perc_18.24))) + 
  geom_sf(color = "black", lwd = 0.25) + 
  theme_void() + scale_fill_gradient(low = "white", high = "blue",
                                     position = "right", name = NULL) +
  labs(title = "% Ratio: 25-64 to 0-24") + 
  theme(plot.subtitle = element_text(face = "italic"),
        plot.title = element_text(face = "bold", hjust = 0),
        plot.margin = margin(l = 7, r = 7))

p2 <- ggplot(counties_demo_map_2010, 
            aes(fill = (perc_25.44 + perc_45.64) / (perc_65p))) + 
  geom_sf(color = "black", lwd = 0.25) + 
  theme_void() + scale_fill_gradient(low = "white", high = "blue",
                                     position = "right", name = NULL) +
  labs(title = "% Ratio: 25-64 to 65+") + 
  theme(plot.subtitle = element_text(face = "italic"),
        plot.title = element_text(face = "bold", hjust = 0),
        plot.margin = margin(l = 7, r = 7))

grid.arrange(p1, p2, nrow = 1)

ggplot(counties_pop_map_2019, aes(fill = persons_per_household)) + 
  geom_sf(color = "black", lwd = 0.25) + 
  theme_void() + scale_fill_gradient(low = "orange", high = "blue",
                                     position = "right", name = NULL) +
  labs(title = "Number of persons per household, by county") + 
  theme(plot.title = element_text(face = "bold", hjust = 0.5))

```

```{r}

## Creating county commissioner district polygons: 2012-2021

voting_dists_19_raw <- readOGR( 
  dsn = paste0(getwd(),"/general_data/shp_bdry_votingdistricts/"), 
  layer = "bdry_votingdistricts",
  verbose = FALSE) 

voting_dists_19_messy <- spTransform(voting_dists_19_raw, 
            CRS("+proj=longlat +datum=WGS84 +no_defs +ellps=WGS84 +towgs84=0,0,0"))

comm_dists_19 <- st_as_sf(voting_dists_19_messy) %>% 
  clean_names() %>%
  st_make_valid() %>% 
  group_by(countyname, countycode, ctycomdist) %>%
  summarize(geometry = st_union(geometry)) %>% 
  ungroup() %>% 
  mutate(countyname = fct_explicit_na(countyname)) %>%
  rename(county_name = countyname) %>% 
  mutate(county_name = as.character(county_name)) %>% 
  rename(county_id = countycode)

# creating map (showing off...)

ggplot(comm_dists_19, aes(fill = ctycomdist)) + 
  geom_sf(color = "grey30", lwd = 0.25) + theme_void() +
  scale_fill_viridis_d() + 
  labs(title = "Only six counties have 7 county commissioner districts:",
       subtitle = "Anoka, Dakota, Hennepin, Olmsted, Ramsey, and St. Louis",
       caption = "map accurate from 2012-2021") + 
  theme(legend.position = "right",
        legend.title = element_blank(),
        legend.text = element_text(face = "bold", size = 7),
        legend.key.size = unit(12, "pt"),
        legend.direction = "vertical",
        plot.margin = margin(b = 10, t = 5),
        plot.title = element_text(face = "bold", size = 9, hjust = 0.5),
        plot.subtitle = element_text(face = "italic", size = 8, hjust = 0.5),
        plot.caption = element_text(face = "italic", size = 6))

```

```{r}

## Creating county commissioner district polygons: 2002-2011

results_10_raw <- readOGR( 
  dsn = paste0(getwd(),"/general_data/2010_precincts_data/"), 
  layer = "elec2010",
  verbose = FALSE)

results_10_messy <- spTransform(results_10_raw, 
            CRS("+proj=longlat +datum=WGS84 +no_defs +ellps=WGS84 +towgs84=0,0,0"))

results_10 <- st_as_sf(results_10_messy) %>% 
  clean_names()

comm_dists_10 <- results_10 %>% 
  rename(precinct_name = precinct,
         ctycomdist = com,
         county_name = county,
         county_id = countycode) %>% 
  mutate(county_name = str_to_title(county_name),
         county_id = fct_explicit_na(county_id)) %>% 
  mutate(county_name = str_replace(county_name, " Of The ", " of the ")) %>% 
  mutate(county_name = str_replace(county_name, " Qui ", " qui ")) %>% 
  select(county_name, county_id, ctycomdist, geometry) %>% 
  st_make_valid() %>% 
  group_by(county_name, county_id, ctycomdist) %>%
  summarize(geometry = st_union(geometry)) %>% 
  ungroup() %>% 
  fill_holes(threshold = units::set_units(25, miles^2)) %>% 
  mutate(ctycomdist = as.factor(ctycomdist)) %>% 
  mutate(county_id = as.factor(county_id))

# creating another map (showing off, again...)

ggplot(comm_dists_10, aes(fill = ctycomdist)) + 
  geom_sf(color = "grey30", lwd = 0.25) + theme_void() +
  scale_fill_viridis_d() + 
  labs(title = "Only six counties have 7 county commissioner districts:",
       subtitle = "Anoka, Dakota, Hennepin, Olmsted, Ramsey, and St. Louis",
       caption = "map accurate from 2002-2011") + 
  theme(legend.position = "right",
        legend.title = element_blank(),
        legend.text = element_text(face = "bold", size = 7),
        legend.key.size = unit(12, "pt"),
        legend.direction = "vertical",
        plot.margin = margin(b = 10, t = 5),
        plot.title = element_text(face = "bold", size = 9, hjust = 0.5),
        plot.subtitle = element_text(face = "italic", size = 8, hjust = 0.5),
        plot.caption = element_text(face = "italic", size = 6))

```

```{r, warning = F}

## Visualizing side-by-side county primary and general elections

comm.elections.df <- function(year, type){
  clean_county(year, type) %>% 
      select(county_id, office_name, district, candidate_name, candidate_votes, 
             candidate_percent_vote, special) %>% 
      filter(office_name == "Commissioner") %>% 
      rename(ctycomdist = district) %>% 
      group_by(county_id, office_name, ctycomdist) %>% 
      summarize(num_candidates = n() - ifelse(type == "general", 1, 0)) %>% 
      ungroup() %>% 
      mutate(ctycomdist = as.factor(ctycomdist)) %>% 
      mutate(county_id = as.factor(county_id))
  }

plot_com_elections <- function(year, type, county){
  
  if(year >= 2012){
    test <- comm_dists_19 %>% 
      full_join(comm.elections.df(year, type), by = c("county_id", "ctycomdist")) %>% 
      select(county_name, county_id, ctycomdist, office_name, num_candidates, geometry) %>% 
      mutate(num_candidates = as.factor(num_candidates))
    }else{
      if(year >= 2002){
        test <- comm_dists_10 %>% 
          full_join(comm.elections.df(year, type), by = c("county_id", "ctycomdist")) %>% 
          select(county_name, county_id, ctycomdist, office_name, num_candidates, geometry) %>% 
          mutate(num_candidates = as.factor(num_candidates))
      }else{
          test <- comm_dists_01 %>% 
            full_join(comm.elections.df(year, type), by = c("county_id", "ctycomdist")) %>% 
            select(county_name, county_id, ctycomdist, office_name, num_candidates, geometry) %>% 
            mutate(num_candidates = as.factor(num_candidates))        
      }
    }
  
  ggplot(test %>% filter(county_name == county), aes(fill = num_candidates)) + 
    geom_sf(color = "grey30", lwd = 0.25) + theme_void() +
    scale_fill_viridis_d() + 
    labs(title = paste0(county, " County:"), 
         subtitle = paste0("Number of Candidates in County ", str_to_title(type), ", ", year)) +
    theme(plot.title = element_text(face = "bold", size = 12, hjust = 0.5),
          plot.subtitle = element_text(face = "italic", size = 8, hjust = 0.5),
          legend.position = "bottom",
          legend.title = element_text(size = 6),
          plot.margin = margin(t = 5, l = 5, b = 10))
  }

side_by_side <- function(year, county){
  grid.arrange(plot_com_elections(year, "primary", county), 
               plot_com_elections(year, "general", county), nrow = 1)
  }

grid.arrange(plot_com_elections(2010, "general", "Dakota"), 
             plot_com_elections(2012, "general", "Dakota"), nrow = 1)

# randomly distribute dots as idea? see: https://www.co.dakota.mn.us/HomeProperty/MappingServices/Maps/Documents/Census2010/PopulationDensityCommissioner.pdf

```

```{r, warning = F}

## Creating county commissioner district polygons: 1992-2001

pres_elections_01 <- read_xls("general_data/01_precincts/2000_general_results.xls") %>% 
  clean_names() %>% 
  mutate(precinct_name = str_to_title(precinct_name)) %>% 
  rename(ctycomdist = cm,
         county_id = cc,
         precinct_id = prct) %>% 
  select(precinct_name, county_id, ctycomdist, precinct_id) %>% 
  full_join(county_ids, by = "county_id")

# cleaning 2001 voting district data, and tweaking based on MNLL maps

vtd_01_raw <- readOGR( 
  dsn = paste0(getwd(),"/general_data/01_precincts/"), 
  layer = "Precincts_DD",
  verbose = FALSE)

proj4string(vtd_01_raw) <- CRS("+proj=longlat +datum=WGS84 +no_defs +ellps=WGS84 +towgs84=0,0,0")

vtd_01_messy <- spTransform(vtd_01_raw, 
            CRS("+proj=longlat +datum=WGS84 +no_defs +ellps=WGS84 +towgs84=0,0,0"))

vtd_01 <- st_as_sf(vtd_01_messy) %>% 
  clean_names()

comm_dists_01 <- vtd_01 %>% 
  select(id:name, index_vote) %>% 
  filter(!name == "Lake Superior") %>%
  mutate(null_votes = ifelse(index_vote %in% c(0.0000, NA), 
                             TRUE, FALSE)) %>% 
  rename(precinct_id = number,
         county_num = county,
         county_name = county_nam,
         precinct_name = name) %>% 
  select(precinct_id, county_num, county_name, precinct_name, 
         geometry, null_votes) %>%
  mutate(precinct_id = str_remove(precinct_id, "^0+")) %>%
  mutate(precinct_id = as.numeric(precinct_id)) %>% 
  arrange(county_name, precinct_id) %>%
  full_join(pres_elections_01, by = c("precinct_id", "county_name")) %>% 
  mutate(ctycomdist = ifelse(is.na(ctycomdist), 8, ctycomdist)) %>% 
  select(!precinct_name.y) %>% 
  select(!county_id) %>% 
  select(!county_num_precincts) %>% 
  full_join(county_ids %>% select(!county_num_precincts), 
            by = "county_name") %>% 
  rename(precinct_name = precinct_name.x) %>% 
  mutate(ctycomdist = ifelse(ctycomdist == 8, 
                             case_when(county_name == "Aitkin" ~ 8, # complex
                                       county_name == "Becker" ~ 2,
                                       county_name == "Beltrami" ~ 4, # has "0"
                                       county_name == "Benton" ~ 2,
                                       county_name == "Blue Earth" ~ 8, # complex
                                       county_name == "Carlton" ~ 4,
                                       county_name == "Carver" ~ 3,
                                       county_name == "Cook" ~ 8, # complex
                                       county_name == "Crow Wing" ~ 5,
                                       county_name == "Dodge" ~ 3,
                                       county_name == "Hennepin" ~ 8, # complex
                                       county_name == "Itasca" ~ 5,
                                       county_name == "Koochiching" ~ 5,
                                       county_name == "Lake of the Woods" ~ 8, # complex; has "0"
                                       county_name == "Le Sueur" ~ 5,
                                       county_name == "Marshall" ~ 5,
                                       county_name == "Mower" ~ 8, # complex
                                       county_name == "Pope" ~ 3,
                                       county_name == "Renville" ~ 3,
                                       county_name == "Sibley" ~ 1,
                                       county_name == "St. Louis" ~ 8, # complex
                                       county_name == "Stearns" ~ 4,
                                       county_name == "Todd" ~ 5,
                                       county_name == "Traverse" ~ 2,
                                       county_name == "Watonwan" ~ 4,
                                       county_name == "Wilkin" ~ 1,
                                       county_name == "Winona" ~ 8, # complex
                                       TRUE ~ 8),
                             ctycomdist)) %>% 
  mutate(ctycomdist = ifelse(ctycomdist %in% c(0, 8), 
                             case_when(county_name == "Aitkin" ~ case_when(
                                          precinct_name == "Northeast Aitkin Unorg." ~ 5,
                                          precinct_name == "Northwest Aitkin Unorg." ~ 5,
                                          precinct_name == "Davidson Unorg." ~ 3,
                                          precinct_name == "Jewett Unorg." ~ 3,
                                          precinct_name == "Southeast Aitkin Unorg." ~ 3,
                                          TRUE ~ 8),
                                       county_name == "Beltrami" ~ case_when(
                                          precinct_name == "Grant Valley Twp." ~ 3,
                                          precinct_name == "Turtle River Twp." ~ 1,
                                          TRUE ~ 8),
                                       county_name == "Blue Earth" ~ case_when(
                                          precinct_name == "Mankato P-21" ~ 4,
                                          precinct_name == "North Mankato" ~ 2,
                                          TRUE ~ 8),
                                       county_name == "Cook" ~ case_when(
                                          precinct_name == "Maple Hill P-4" ~ 4,
                                          precinct_name == "Grand Marais East P-5" ~ 2,
                                          precinct_name == "Colvill P-3" ~ 1,
                                          precinct_name == "Lutsen P-8" ~ 5,
                                          TRUE ~ 8),
                                       county_name == "Hennepin" ~ case_when(
                                          precinct_name == "Chanhassen P-5" ~ 7,
                                          precinct_name == "Crystal W-2 P-4" ~ 1,
                                          precinct_name == "Hopkins P-9" ~ 6,
                                          TRUE ~ 8),
                                       county_name == "Lake" ~ case_when(
                                          precinct_name == "Beaver Bay" ~ 2,
                                          TRUE ~ 8),
                                       county_name == "Lake of the Woods" ~ case_when(
                                          precinct_name == "Prosper Unorg. P-5A" ~ 4,
                                          precinct_name == "Lakewood Unorg. P-5A" ~ 5,
                                          precinct_name == "McDougald Unorg. P-4B" ~ 4,
                                          precinct_name == "Wheeler Unorg. P-4A" ~ 4,
                                          precinct_name == "Potamo Unorg. P-3C" ~ 3,
                                          precinct_name == "McDougald Unorg. P-3C" ~ 5,
                                          precinct_name == "Spooner Unorg. P-3B" ~ 3,
                                          precinct_name == "Walhalla Unorg. P-3B" ~ 3,
                                          precinct_name == "Victory Unorg. P-3B" ~ 3,
                                          precinct_name == "Rulien Unorg. P-3B" ~ 3,
                                          precinct_name == "Unorg. 158-30 P-2C" ~ 2,
                                          precinct_name == "Unorg. 157-30 P-2C" ~ 2,
                                          precinct_name == "Swiftwater Unorg. P-2C" ~ 2,
                                          precinct_name == "Kiel Unorg. P-2C" ~ 2,
                                          precinct_name == "Rapid River Unorg. P-2A" ~ 2,
                                          TRUE ~ 8),
                                       county_name == "Mower" ~ case_when(
                                          precinct_name == "Austin W-2 P-3" ~ 5,
                                          precinct_name == "Austin W-3 P-3" ~ 4,
                                          TRUE ~ 8),
                                       county_name == "St. Louis" ~ case_when(
                                          precinct_name == "Meadowlands Twp." ~ 7,
                                          precinct_name == "Marion Lake" ~ 6,
                                          precinct_name == "Sunday Lake Unorg." ~ 4,
                                          precinct_name == "Angleworm Lake Unorg." ~ 4,
                                          TRUE ~ 8),
                                       county_name == "Winona" ~ case_when(
                                          precinct_name == "Winona W-4 P-5" ~ 2,
                                          precinct_name == "La Crescent" ~ 5,
                                          TRUE ~ 8),
                                       TRUE ~ 8
                                      ),
                             ctycomdist)) %>% 
  st_make_valid() %>%
  group_by(county_name, county_id, ctycomdist) %>%
  summarize(geometry = st_union(geometry)) %>% 
  ungroup() %>% 
  mutate(ctycomdist = as.factor(ctycomdist))
  
# creating yet another map (the hardest one yet...)

ggplot(comm_dists_01, aes(fill = ctycomdist)) + 
  geom_sf(color = "grey30", lwd = 0.25) + theme_void() +
  scale_fill_viridis_d() + 
  labs(title = "Only six counties have 7 county commissioner districts:",
       subtitle = "Anoka, Dakota, Hennepin, Olmsted, Ramsey, and St. Louis",
       caption = "map accurate from 1992-2001") + 
  theme(legend.position = "right",
        legend.title = element_blank(),
        legend.text = element_text(face = "bold", size = 7),
        legend.key.size = unit(12, "pt"),
        legend.direction = "vertical",
        plot.margin = margin(b = 10, t = 5),
        plot.title = element_text(face = "bold", size = 9, hjust = 0.5),
        plot.subtitle = element_text(face = "italic", size = 8, hjust = 0.5),
        plot.caption = element_text(face = "italic", size = 6))

```


```{r}

## Side-by-side county redistricting visualizer

ctycomdists_time <- rbind(comm_dists_01 %>% mutate(year = 1991), 
                          comm_dists_10 %>% mutate(year = 2001), 
                          comm_dists_19 %>% mutate(year = 2011))

cty_redistricting <- function(countynam){
  ctycomdists_time %>% filter(county_name == countynam) %>% 
    ggplot(aes(fill = ctycomdist)) + geom_sf() + facet_grid(~ year) + 
    theme_void() + labs(fill = "County Comm. Dist.",
                        title = paste0("30 Years of ", countynam, 
                                       " County Redistricting"),
      subtitle = "County commissioner districts are reassessed decennially with the U.S. Census") +
    theme(plot.title = element_text(face = "bold", size = 16, 
                                    hjust = 0.5, margin = margin(b = 6)),
          plot.subtitle = element_text(face = "italic", size = 10, 
                                       hjust = 0.5, margin = margin(b = 12)),
          legend.position = "bottom",
          legend.title = element_text(face = "bold.italic", size = 8),
          strip.text = element_text(face = "bold", size = 10),
          plot.margin = margin(t = 8, l = 5, r = 5, b = 5),
          legend.text = element_text(face = "bold", size = 7),
          legend.key.size = unit(12, "pt"),
          legend.direction = "horizontal") + 
    scale_fill_brewer(palette = "Set2") +
    guides(fill = guide_legend(nrow = 1, byrow = TRUE, 
                               title.position = "bottom", title.hjust = 0.5))
  }

cty_redistricting("Crow Wing")

```



```{r}

comm_dists_01_mod <- vtd_01 %>% 
  select(id:name, index_vote) %>% 
  filter(!name == "Lake Superior") %>%
  mutate(null_votes = ifelse(index_vote %in% c(0.0000, NA), 
                             TRUE, FALSE)) %>% 
  rename(precinct_id = number,
         county_num = county,
         county_name = county_nam,
         precinct_name = name) %>% 
  select(precinct_id, county_num, county_name, precinct_name, 
         geometry, null_votes) %>%
  mutate(precinct_id = str_remove(precinct_id, "^0+")) %>%
  mutate(precinct_id = as.numeric(precinct_id)) %>% 
  arrange(county_name, precinct_id) %>%
  full_join(pres_elections_01, by = c("precinct_id", "county_name")) %>% 
  mutate(ctycomdist = ifelse(is.na(ctycomdist), 8, ctycomdist)) %>% 
  select(!precinct_name.y) %>% 
  select(!county_id) %>% 
  select(!county_num_precincts) %>% 
  full_join(county_ids %>% select(!county_num_precincts), 
            by = "county_name") %>% 
  rename(precinct_name = precinct_name.x) %>% 
  mutate(ctycomdist = ifelse(ctycomdist == 8, 
                             case_when(county_name == "Aitkin" ~ 8, # complex
                                       county_name == "Becker" ~ 2,
                                       county_name == "Beltrami" ~ 4, # has "0"
                                       county_name == "Benton" ~ 2,
                                       county_name == "Blue Earth" ~ 8, # complex
                                       county_name == "Carlton" ~ 4,
                                       county_name == "Carver" ~ 3,
                                       county_name == "Cook" ~ 8, # complex
                                       county_name == "Crow Wing" ~ 5,
                                       county_name == "Dodge" ~ 3,
                                       county_name == "Hennepin" ~ 8, # complex
                                       county_name == "Itasca" ~ 5,
                                       county_name == "Koochiching" ~ 5,
                                       county_name == "Lake of the Woods" ~ 8, # complex; has "0"
                                       county_name == "Le Sueur" ~ 5,
                                       county_name == "Marshall" ~ 5,
                                       county_name == "Mower" ~ 8, # complex
                                       county_name == "Pope" ~ 3,
                                       county_name == "Renville" ~ 3,
                                       county_name == "Sibley" ~ 1,
                                       county_name == "St. Louis" ~ 8, # complex
                                       county_name == "Stearns" ~ 4,
                                       county_name == "Todd" ~ 5,
                                       county_name == "Traverse" ~ 2,
                                       county_name == "Watonwan" ~ 4,
                                       county_name == "Wilkin" ~ 1,
                                       county_name == "Winona" ~ 8, # complex
                                       TRUE ~ 8),
                             ctycomdist)) %>% 
  mutate(ctycomdist = ifelse(ctycomdist %in% c(0, 8), 
                             case_when(county_name == "Aitkin" ~ case_when(
                                          precinct_name == "Northeast Aitkin Unorg." ~ 5,
                                          precinct_name == "Northwest Aitkin Unorg." ~ 5,
                                          precinct_name == "Davidson Unorg." ~ 3,
                                          precinct_name == "Jewett Unorg." ~ 3,
                                          precinct_name == "Southeast Aitkin Unorg." ~ 3,
                                          TRUE ~ 8),
                                       county_name == "Beltrami" ~ case_when(
                                          precinct_name == "Grant Valley Twp." ~ 3,
                                          precinct_name == "Turtle River Twp." ~ 1,
                                          TRUE ~ 8),
                                       county_name == "Blue Earth" ~ case_when(
                                          precinct_name == "Mankato P-21" ~ 4,
                                          precinct_name == "North Mankato" ~ 2,
                                          TRUE ~ 8),
                                       county_name == "Cook" ~ case_when(
                                          precinct_name == "Maple Hill P-4" ~ 4,
                                          precinct_name == "Grand Marais East P-5" ~ 2,
                                          precinct_name == "Colvill P-3" ~ 1,
                                          precinct_name == "Lutsen P-8" ~ 5,
                                          TRUE ~ 8),
                                       county_name == "Hennepin" ~ case_when(
                                          precinct_name == "Chanhassen P-5" ~ 7,
                                          precinct_name == "Crystal W-2 P-4" ~ 1,
                                          precinct_name == "Hopkins P-9" ~ 6,
                                          TRUE ~ 8),
                                       county_name == "Lake" ~ case_when(
                                          precinct_name == "Beaver Bay" ~ 2,
                                          TRUE ~ 8),
                                       county_name == "Lake of the Woods" ~ case_when(
                                          precinct_name == "Prosper Unorg. P-5A" ~ 4,
                                          precinct_name == "Lakewood Unorg. P-5A" ~ 5,
                                          precinct_name == "McDougald Unorg. P-4B" ~ 4,
                                          precinct_name == "Wheeler Unorg. P-4A" ~ 4,
                                          precinct_name == "Potamo Unorg. P-3C" ~ 3,
                                          precinct_name == "McDougald Unorg. P-3C" ~ 5,
                                          precinct_name == "Spooner Unorg. P-3B" ~ 3,
                                          precinct_name == "Walhalla Unorg. P-3B" ~ 3,
                                          precinct_name == "Victory Unorg. P-3B" ~ 3,
                                          precinct_name == "Rulien Unorg. P-3B" ~ 3,
                                          precinct_name == "Unorg. 158-30 P-2C" ~ 2,
                                          precinct_name == "Unorg. 157-30 P-2C" ~ 2,
                                          precinct_name == "Swiftwater Unorg. P-2C" ~ 2,
                                          precinct_name == "Kiel Unorg. P-2C" ~ 2,
                                          precinct_name == "Rapid River Unorg. P-2A" ~ 2,
                                          TRUE ~ 8),
                                       county_name == "Mower" ~ case_when(
                                          precinct_name == "Austin W-2 P-3" ~ 5,
                                          precinct_name == "Austin W-3 P-3" ~ 4,
                                          TRUE ~ 8),
                                       county_name == "St. Louis" ~ case_when(
                                          precinct_name == "Meadowlands Twp." ~ 7,
                                          precinct_name == "Marion Lake" ~ 6,
                                          precinct_name == "Sunday Lake Unorg." ~ 4,
                                          precinct_name == "Angleworm Lake Unorg." ~ 4,
                                          TRUE ~ 8),
                                       county_name == "Winona" ~ case_when(
                                          precinct_name == "Winona W-4 P-5" ~ 2,
                                          precinct_name == "La Crescent" ~ 5,
                                          TRUE ~ 8),
                                       TRUE ~ 8
                                      ),
                             ctycomdist)) %>% 
# simple fixes!!
  mutate(ctycomdist = case_when(county_name == "Crow Wing" ~ ifelse(precinct_name == 
                                                                      "Davenport Prec",
                                                                    4, ctycomdist),
                                TRUE ~ ctycomdist), 
                             ctycomdist) %>% 
  mutate(ctycomdist = as.factor(ctycomdist))

comm_dists_01_mod %>% filter(county_name == "Roseau") %>% 
    ggplot(aes(fill = ctycomdist)) + geom_sf() + #geom_sf_label(aes(label = precinct_name)) +
  scale_fill_brewer(palette = "Set2")


# advanced fixes needed: Aitkin, Becker, Beltrami, Big Stone, Brown, Carlton, Cass, Chisago,
 # Cook, Freeborn, Goodhue, Isanti, Itasca, Kittson, Koochiching, Lac qui Parle, 
 # Lake of the Woods, Mahnomen, Marshall, Martin, Meeker, Mower, Nicollet, Nobles, 
 # Olmsted, Otter Tail, Pipestone, Polk, Pope, Ramsey, Redwood, 

```












