
Appendix for "Scraping County-Level Election Results Data":

```{r, include = F, eval = F}

## Loading necessary packages...

library(BBmisc)
library(rvest)
library(janitor)
library(tidyverse)

```

```{r, include = F, eval = F}

## Functions for collecting 2002 general election county data

county_stats_2002 <- function(county_id){
  url <- paste0("https://electionresults.sos.state.mn.us",
                "/results/Index?ErsElectionId=32&scenario=LocalCounty&CountyId=", 
                county_id)

  numbers <- tibble(headers = head(as.vector(html_text(html_nodes(read_html(url), 
                                                              'span.boldFont'))), 3),
         data = tail(head(as.vector(html_text(html_nodes(read_html(url), 
                                                    'div.flex-container div'))), 4), 3)) %>% 
    filter(!headers == "Last Updated:") %>% 
    mutate(data = str_remove_all(data, "\r\n")) %>% 
    mutate(data = str_remove(data, "Precincts Reporting in County:")) %>% 
    mutate(data = str_remove(data, "Voters Registered at 7AM:"))
  
  tibble(num_precincts_reporting = 
           round((as.numeric(str_trim(str_extract(numbers$data[1], "[^%]+")))/100)*
            as.numeric(str_extract(str_trim(numbers$data[1]), "[0-9]+$"))), 
         total_num_precincts_voting = 
           as.numeric(str_extract(str_trim(numbers$data[1]), "[0-9]+$")))
  
}

county_unclean_2002_general <- function(county_id){
  url <- paste0("https://electionresults.sos.state.mn.us",
                "/results/Index?ErsElectionId=32&scenario=LocalCounty&CountyId=", 
                county_id)

  data <- tibble(numbers_filler = as.vector(html_text(html_nodes(read_html(url), 
                                               'td.col-md-2.col-sm-2.col-xs-2.text-right'))))
  
  leng <- length(as.vector(html_text(html_nodes(read_html(url), 'span.boldFont'))))
  
  repeat_this <- nrow(data)
  
  table_draft <- data %>% mutate(every_other = rep(c("candidate_votes", 
                                                     "candidate_percent_vote"), 
                                                   repeat_this/2),
                  county_num_precincts_reporting = 
                    rep(county_stats_2002(county_id)$num_precincts_reporting[1],
                                                repeat_this),
                  county_total_num_precincts_voting = 
                    rep(county_stats_2002(county_id)$total_num_precincts_voting[1],
                                                repeat_this)) %>% 
    mutate(numbers_filler = as.numeric(str_remove_all(numbers_filler, "%|,")),
           unique_num = rep(1:(repeat_this/2), each = 2)) %>% 
    pivot_wider(names_from = "every_other", values_from = "numbers_filler") %>% 
    mutate(candidate_name = as.vector(html_text(html_nodes(read_html(url), 
                                          'td.col-md-3.col-sm-3.col-xs-3'))),
           county_id = rep(county_id, repeat_this/2)) %>% 
    mutate(party_affiliation = 
             ifelse(grepl("WRITE-IN|\\bNO\\b|\\bAGAINST\\b", 
                                            candidate_name), "WI", "NP")) %>% 
    select(county_id, candidate_name, party_affiliation, 
           county_num_precincts_reporting,
           county_total_num_precincts_voting, candidate_votes, 
           candidate_percent_vote, unique_num) 
    
  table_draft <- if(county_id == 45){
    table_draft %>% 
      filter(!unique_num %in% c(21, 22)) %>% 
      select(!unique_num) %>% rowid_to_column() %>% 
      rename(unique_num = rowid)
    }else{
          table_draft
    }
  
  differ <- diff(sort(append(as.vector(unlist(as.vector(table_draft %>% 
                                                          filter(party_affiliation =="WI") %>% 
                                                          select(unique_num)))), 0))) 
  
  if(county_id == 56){
    cand <- append(tail(as.vector(html_text(html_nodes(read_html(url), 'span.boldFont'))), 
                        leng - 6), "SOIL AND WATER SUPERVISOR DISTRICT 2 (2)",
                   after = 9)
      }else{
        if(county_id == 45){
          cand <- tail(as.vector(html_text(html_nodes(read_html(url), 'span.boldFont'))), 
                     leng - 6)[-9:-10]
          }else{
        cand <- tail(as.vector(html_text(html_nodes(read_html(url), 'span.boldFont'))), 
                     leng - 6)
    }}
  
  allocate <- tibble(count = differ,
                     cand = cand)
  allo_column <- as.tibble(as.vector(unlist(mapply(rep, allocate$cand, allocate$count))))
  
  cbind(allo_column, table_draft) %>% select(!unique_num) %>% rename(office_name = value) %>% 
    mutate(party_affiliation = ifelse(grepl("\\bNO\\b|\\bAGAINST\\b", 
                                            candidate_name), "NP", party_affiliation))
    
}

```

```{r, include = F, eval = F}

## Functions for collecting 2000 general election county data

county_stats_2000 <- function(county_id){
  url <- paste0("https://electionresults.sos.state.mn.us",
                "/results/Index?ErsElectionId=22&scenario=LocalCounty&CountyId=", 
                county_id)

  numbers <- tibble(headers = head(as.vector(html_text(html_nodes(read_html(url), 
                                                              'span.boldFont'))), 3),
         data = tail(head(as.vector(html_text(html_nodes(read_html(url), 
                                                    'div.flex-container div'))), 4), 3)) %>% 
    filter(!headers == "Last Updated:") %>% 
    mutate(data = str_remove_all(data, "\r\n")) %>% 
    mutate(data = str_remove(data, "Precincts Reporting in County:")) %>% 
    mutate(data = str_remove(data, "Voters Registered at 7AM:"))
  
  tibble(num_precincts_reporting = 
           round((as.numeric(str_trim(str_extract(numbers$data[1], "[^%]+")))/100)*
            as.numeric(str_extract(str_trim(numbers$data[1]), "[0-9]+$"))), 
         total_num_precincts_voting = 
           as.numeric(str_extract(str_trim(numbers$data[1]), "[0-9]+$")))
  
}

county_unclean_2000_general <- function(county_id){
  url <- paste0("https://electionresults.sos.state.mn.us",
                "/results/Index?ErsElectionId=22&scenario=LocalCounty&CountyId=", 
                county_id)
    
  data <- tibble(numbers_filler = as.vector(html_text(html_nodes(read_html(url), 
                                               'td.col-md-2.col-sm-2.col-xs-2.text-right'))))
  
  leng <- length(as.vector(html_text(html_nodes(read_html(url), 'span.boldFont'))))
  
  repeat_this <- nrow(data)
  
  table_draft <- data %>% mutate(every_other = rep(c("candidate_votes", 
                                                     "candidate_percent_vote"), 
                                                   repeat_this/2),
                  county_num_precincts_reporting = 
                    rep(county_stats_2002(county_id)$num_precincts_reporting[1],
                                                repeat_this),
                  county_total_num_precincts_voting = 
                    rep(county_stats_2002(county_id)$total_num_precincts_voting[1],
                                                repeat_this)) %>% 
    mutate(numbers_filler = as.numeric(str_remove_all(numbers_filler, "%|,")),
           unique_num = rep(1:(repeat_this/2), each = 2)) %>% 
    pivot_wider(names_from = "every_other", values_from = "numbers_filler") %>% 
    mutate(candidate_name = as.vector(html_text(html_nodes(read_html(url), 
                                          'td.col-md-3.col-sm-3.col-xs-3'))),
           county_id = rep(county_id, repeat_this/2)) %>% 
    mutate(party_affiliation = 
             ifelse(grepl("WRITE.*IN|\\bNO\\b|\\bAGAINST\\b", 
                                            candidate_name), "WI", "NP")) %>% 
    select(county_id, candidate_name, party_affiliation, 
           county_num_precincts_reporting, county_total_num_precincts_voting, 
           candidate_votes, candidate_percent_vote, unique_num) 

  if(county_id == 21){
      table_draft <- table_draft %>% 
        mutate(unique_num = ifelse(candidate_votes == 11882, 2, unique_num)) %>% 
        mutate(unique_num = ifelse(candidate_votes == 3768, 3, unique_num)) %>% 
        mutate(unique_num = ifelse(candidate_votes == 7599, 4, unique_num)) %>% 
        mutate(unique_num = ifelse(candidate_votes == 3455, 5, unique_num)) %>% 
        mutate(unique_num = ifelse(candidate_votes == 11867, 6, unique_num)) %>% 
        arrange(unique_num)
      }else{
        if(county_id == 16){
             table_draft <- table_draft %>% 
               mutate(unique_num = ifelse(candidate_votes == 624, 1, unique_num)) %>% 
               mutate(unique_num = ifelse(candidate_votes == 2103, 2, unique_num)) %>% 
               mutate(unique_num = ifelse(candidate_votes == 732, 3, unique_num)) %>% 
               arrange(unique_num)          
        }else{
          if(county_id == 59){
               table_draft <- table_draft %>% 
                 mutate(unique_num = ifelse(candidate_votes == 2844, 1, unique_num)) %>% 
                 mutate(unique_num = ifelse(candidate_votes == 1955, 2, unique_num)) %>% 
                 mutate(unique_num = ifelse(candidate_votes == 2617, 3, unique_num)) %>% 
                 arrange(unique_num)
          }else{
            if(county_id == 62){
                table_draft <- table_draft %>% 
                  mutate(unique_num = ifelse(candidate_votes == 152536, 1, unique_num)) %>% 
                  mutate(unique_num = ifelse(candidate_votes == 60829, 2, unique_num)) %>% 
                  mutate(unique_num = ifelse(candidate_votes == 155844, 3, unique_num)) %>% 
                  arrange(unique_num)
            }else{
              table_draft <- table_draft
    }}}}
  
  differ <- diff(sort(append(as.vector(unlist(as.vector(table_draft %>% 
                                                          filter(party_affiliation == "WI") %>% 
                                                          select(unique_num)))), 0))) 

  if(county_id == 21){
    cand <- as.vector(tail(as.vector(html_text(html_nodes(read_html(url), 'span.boldFont'))), 
                        leng - 6))[-4:-5]
      }else{
        if(county_id == 56){
          cand <- tail(as.vector(html_text(html_nodes(read_html(url), 'span.boldFont'))), 
                      leng - 6)[-5]
        }else{
          if(county_id %in% c(16, 59, 62)){
            cand <- as.vector(tail(as.vector(html_text(html_nodes(read_html(url), 
                                                                  'span.boldFont'))), 
                        leng - 6))[-1]
          }else{
            cand <- tail(as.vector(html_text(html_nodes(read_html(url), 'span.boldFont'))), 
                        leng - 6)
    }}}

  allocate <- tibble(count = differ,
                     cand = cand)
  allo_column <- as.tibble(as.vector(unlist(mapply(rep, allocate$cand, allocate$count))))
  
  cbind(allo_column, table_draft) %>% select(!unique_num) %>% rename(office_name = value) %>% 
    mutate(party_affiliation = ifelse(grepl("\\bNO\\b|\\bAGAINST\\b", 
                                            candidate_name), "NP", party_affiliation))

}

```

```{r, include = F, eval = F}

## Functions for collecting 2000 primary election county data

grab_2000_primary_counties <- function(){
  url <- paste0("https://electionresults.sos.state.mn.us/21")

  counties_w_primaries_names <- tibble(county_name = 
                                        as.vector(html_text(html_nodes(read_html(url), 
                                          'select#countySelect.form-control option')))) %>% 
    mutate(county_name = str_replace(county_name, " Of The ", " of the ")) %>% 
    mutate(county_name = str_replace(county_name, " Qui ", " qui ")) %>% 
    filter(!county_name == "Select a County")

  county_ids %>% 
    inner_join(counties_w_primaries_names, by = "county_name") %>% 
    select(!county_name:county_num_precincts) %>% 
    unlist() %>% 
    as.vector()

}

county_stats_2000_primary <- function(county_id){
  url <- paste0("https://electionresults.sos.state.mn.us",
                "/results/Index?ErsElectionId=21&scenario=LocalCounty&CountyId=", 
                county_id, "&show=Go")

  numbers <- tibble(data = head(as.vector(html_text(html_nodes(read_html(url), 
                                                    'div.flex-container div'))), 1)) %>% 
    mutate(data = str_remove_all(data, "Last Updated:.*")) %>% 
    mutate(data = str_remove_all(data, "\r\n")) %>% 
    mutate(data = str_trim(str_remove(data, ".*%"), side = "both"))
  
  numbers %>% separate(data, sep = "of",
           into = c("num_precincts_reporting", "total_num_precincts_voting")) %>% 
    mutate(num_precincts_reporting = 
             as.numeric(str_trim(num_precincts_reporting)),
           total_num_precincts_voting = 
             as.numeric(str_trim(total_num_precincts_voting))) 
  
}

check.integer <- function(x) {
    x == round(x)
}

county_unclean_2000_primary <- function(county_id){
  url <- paste0("https://electionresults.sos.state.mn.us",
                "/results/Index?ErsElectionId=21&scenario=LocalCounty&CountyId=", 
                county_id, "&show=Go")
    
  data <- tibble(numbers_filler = as.vector(html_text(html_nodes(read_html(url), 
                                               'td.col-md-2.col-sm-2.col-xs-2.text-right'))))
  
  leng <- length(as.vector(html_text(html_nodes(read_html(url), 'span.boldFont'))))
  
  repeat_this <- nrow(data)
  
  table_draft1 <- data %>% mutate(every_other = rep(c("candidate_votes", 
                                                     "candidate_percent_vote"), 
                                                   repeat_this/2),
                  county_num_precincts_reporting = 
                    rep(county_stats_2000_primary(county_id)$num_precincts_reporting[1],
                                                repeat_this),
                  county_total_num_precincts_voting = 
                    rep(county_stats_2000_primary(county_id)$total_num_precincts_voting[1],
                                                repeat_this)) %>% 
    mutate(numbers_filler = as.numeric(str_remove_all(numbers_filler, "%|,")),
           unique_num = rep(1:(repeat_this/2), each = 2)) %>% 
    pivot_wider(names_from = "every_other", values_from = "numbers_filler") %>% 
    mutate(candidate_name = as.vector(html_text(html_nodes(read_html(url), 
                                          'td.col-md-3'))),
           county_id = rep(county_id, repeat_this/2)) %>% 
    mutate(party_affiliation = 
             ifelse(grepl("WRITE.*IN|\\bNO\\b|\\bAGAINST\\b", 
                                            candidate_name), "WI", "NP")) %>% 
    select(county_id, candidate_name, party_affiliation, 
           county_num_precincts_reporting, county_total_num_precincts_voting, 
           candidate_votes, candidate_percent_vote, unique_num) 
  
  table_draft <- table_draft1 %>% 
    mutate(perc_tot = cumsum(candidate_percent_vote)) %>% 
    mutate(perc_tot = ifelse(perc_tot %in% c("99.99", "100.01"), 100, perc_tot)) %>% 
    mutate(perc_tot = ifelse(perc_tot %in% c("199.98", "199.99", 
                                             "200.01", "200.02"), 200, perc_tot)) %>% 
    mutate(perc_tot = ifelse(perc_tot %in% c("299.98", "299.99", 
                                             "300.01", "300.02"), 300, perc_tot)) %>% 
    mutate(end.key = ifelse(check.integer(perc_tot/100), TRUE, FALSE))
  
  differ <- diff(sort(append(as.vector(unlist(as.vector(table_draft %>% 
                                                          filter(end.key == TRUE) %>% 
                                                          select(unique_num)))), 0))) 
  
  cand <- tail(as.vector(html_text(html_nodes(read_html(url), 'span.boldFont'))), 
                leng - 4)

  allocate <- tibble(count = differ,
                     cand = cand)
  allo_column <- as_tibble(as.vector(unlist(mapply(rep, allocate$cand, allocate$count))))
  
  cbind(allo_column, table_draft) %>% select(!unique_num) %>% 
    select(!end.key) %>% 
    select(!perc_tot) %>% 
    rename(office_name = value) %>% 
    mutate(party_affiliation = ifelse(grepl("\\bNO\\b|\\bAGAINST\\b", 
                                            candidate_name), "NP", party_affiliation))

}

```


```{r, include = F, eval = F}

# Testing for errors: 2002 general election scraping

test_for_errors_02 <- function(county_id){
  is.error(county_unclean_2002_general(county_id))
}

county_id_numbers <- tibble(county_id = 1:87) %>% 
  mutate(error = map_lgl(county_id, test_for_errors_02))

# Testing for errors: 2000 general election scraping

test_for_errors_00 <- function(county_id){
  is.error(county_unclean_2000_general(county_id))
}

county_id_numbers <- tibble(county_id = 1:87) %>% 
  mutate(error = map_lgl(county_id, test_for_errors_00))

# Testing for errors: 2000 primary election scraping

test_for_errors_00_prim <- function(county_id){
  is.error(county_unclean_2000_primary(county_id))
}

county_id_numbers <- tibble(county_id = grab_2000_primary_counties()) %>% 
  mutate(error = map_lgl(county_id, test_for_errors_00_prim))

```

```{r, include = F, eval = F}

## Writing 2002 general election data to a .txt file

datalist2002 = list()

for(i in 1:87){
  dat <- county_unclean_2002_general(i)
  datalist2002[[i]] <- dat
}

county_gen_2002 <- do.call(rbind, datalist2002)

county_gen_2002_clean <- county_gen_2002 %>% 
  mutate(state = "MN",
         county_id = sprintf("%02d", county_id),
         precinct_name = NA,
         office_id = NA,
         district = NA,
         candidate_order_code = NA,
         suffix = NA,
         incumbent_code = NA,
         total_race_votes = NA) %>% 
  select(state, county_id, precinct_name, office_id, office_name, district,
         candidate_order_code, candidate_name, suffix, incumbent_code, 
         party_affiliation, county_num_precincts_reporting,
         county_total_num_precincts_voting, candidate_votes, candidate_percent_vote,
         total_race_votes)

write.table(county_gen_2002_clean, 
            file = "relevant_county_data/county_races_datasets/2002_county_gen.txt", 
            sep = ";", col.names = TRUE, quote = FALSE, row.names = FALSE)

```

```{r, include = F, eval = F}

## Writing 2000 general election data to a .txt file

datalist2000 = list()

for(i in 1:87){
  dat <- county_unclean_2000_general(i)
  datalist2000[[i]] <- dat
}

county_gen_2000 <- do.call(rbind, datalist2000)

county_gen_2000_clean <- county_gen_2000 %>% 
  mutate(state = "MN",
         county_id = sprintf("%02d", county_id),
         precinct_name = NA,
         office_id = NA,
         district = NA,
         candidate_order_code = NA,
         suffix = NA,
         incumbent_code = NA,
         total_race_votes = NA) %>% 
  mutate(candidate_name = str_trim(candidate_name, side = "right")) %>% 
  select(state, county_id, precinct_name, office_id, office_name, district,
         candidate_order_code, candidate_name, suffix, incumbent_code, 
         party_affiliation, county_num_precincts_reporting,
         county_total_num_precincts_voting, candidate_votes, candidate_percent_vote,
         total_race_votes)

write.table(county_gen_2000_clean, 
            file = "relevant_county_data/county_races_datasets/2000_county_gen.txt", 
            sep = ";", col.names = TRUE, quote = FALSE, row.names = FALSE)

```

```{r, include = F, eval = F}

## Writing 2000 primary election data to a .txt file

datalist2000_prim = list()

vector <- grab_2000_primary_counties()

for(i in 1:50){
  dat <- county_unclean_2000_primary(vector[i])
  datalist2000_prim[[i]] <- dat
}

county_prim_2000 <- do.call(rbind, datalist2000_prim)

county_prim_2000_clean <- county_prim_2000 %>% 
  mutate(state = "MN",
         county_id = sprintf("%02d", county_id),
         precinct_name = NA,
         office_id = NA,
         district = NA,
         candidate_order_code = NA,
         suffix = NA,
         incumbent_code = NA,
         total_race_votes = NA) %>% 
  select(state, county_id, precinct_name, office_id, office_name, district,
         candidate_order_code, candidate_name, suffix, incumbent_code, 
         party_affiliation, county_num_precincts_reporting,
         county_total_num_precincts_voting, candidate_votes, candidate_percent_vote,
         total_race_votes)

write.table(county_prim_2000_clean, 
            file = "relevant_county_data/county_races_datasets/2000_county_primary.txt", 
            sep = ";", col.names = TRUE, quote = FALSE, row.names = FALSE)

```
